export {default as Brush} from './brush.svg?react'
export {default as Rectangle} from './rectangle.svg?react'
export {default as Circle} from './circle.svg?react'
export {default as Eraser} from './eraser.svg?react'
export {default as Redo} from './redo.svg?react'
export {default as Undo} from './undo.svg?react'
export {default as Save} from './save.svg?react'
